moderator_page:
    path:     /moderator
    defaults: { _controller: 'mgbs\Controller\IndexController::moderatorAction' }
admin_page:
    path:     /admin
    defaults: { _controller: 'mgbs\Controller\IndexController::adminAction' }
rest_buzzer:
    path:       /buzzer/{buzzer}
    defaults: { _controller: 'mgbs\Controller\Rest\BuzzerController::buzzerAction' }
rest_get_all_answers:
    path:       /api/getAllAnswers
    defaults: { _controller: 'mgbs\Controller\Rest\QuestionController::getAllAnswersAction' }
rest_set_question_open_close:
    path:       /api/setQuestionOpen/{questionId}
    requirements:
        questionId: '\d+'
    defaults: { _controller: 'mgbs\Controller\Rest\QuestionController::setQuestionOpenAction' }
rest_get_single_question_from_gameplay:
    path:       /api/getQuestion/{questionId}
    requirements:
        questionId: '\d+'
    defaults: { _controller: 'mgbs\Controller\Rest\QuestionController::setQuestionOpenAction' }
rest_get_all_player_events:
    path:       /api/getAllPlayerEvents
    defaults: { _controller: 'mgbs\Controller\Rest\QuestionController::getAllPlayerEventsAction' }
landing_page:
    path:     /
    defaults: { _controller: 'mgbs\Controller\IndexController::indexAction' }
