moderator_page:
    path:     /moderator
    defaults: { _controller: 'mgbs\Controller\IndexController::moderatorAction' }
admin_page:
    path:     /admin
    defaults: { _controller: 'mgbs\Controller\IndexController::adminAction' }
rest_buzzer:
    path:       /api/insertBuzzer/{buzzer}
    defaults: { _controller: 'mgbs\Controller\Rest\BuzzerController::buzzerAction' }
rest_get_all_answers:
    path:       /api/getAllAnswers
    defaults: { _controller: 'mgbs\Controller\Rest\QuestionController::getAllAnswersAction' }
rest_set_question_open:
    path:       /api/setQuestionOpen/{questionId}
    requirements:
        questionId: '\d+'
    defaults: { _controller: 'mgbs\Controller\Rest\GameEventController::setQuestionOpenAction' }
rest_get_all_player_events:
    path:       /api/getAllGameEvents
    defaults: { _controller: 'mgbs\Controller\Rest\GameEventController::getAllGameEventsAction' }
landing_page:
    path:     /
    defaults: { _controller: 'mgbs\Controller\IndexController::indexAction' }
