services:
  database:
    class: mgbs\Library\Database\DatabaseFactory
    arguments: [ "%db_type%", "%db_path%", "%db_sqlite_file%"]

  questionmodel:
    class: mgbs\Model\QuestionsModel
    arguments: ['@database']
    calls:
        - [setTableName, ['questions']]

  gameeventsmodel:
    class: mgbs\Model\GameEventsModel
    arguments: ['@database']
    calls:
    - [setTableName, ['gameevents']]
