language: php

cache:
  directories:
    - test/elm-stuff/build-artifacts

php:
  - '7.3'

before_script:
  - cd ${TRAVIS_BUILD_DIR}/Code/PHP
  - composer install

script:
  - php vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 Controller/ Library/ Model/ ValueObject/
  - vendor/phpunit/phpunit/phpunit --configuration phpunit.xml Tests
  - vendor/bin/phpstan analyse Controller Library Model DTO View

