language: php
php:
  - '7.1'
  - '7.2'
before_script:
  - cd Code
  - composer install
script:
  - php vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 Controller/ Library/ Model/ ValueObject/
  - Code/vendor/phpunit/phpunit/phpunit --no-configuration /var/www/jeopardy/Code/Tests
