version: "2.0"
services:
  jeophardy_nginx:
    image: nginx:latest
    volumes:
      - ../Code/:/var/www/jeophpardy
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "80:80"
    links:
      - jeophpardy_php
      - jeophpardy_db

  jeophpardy_php:
      build:
        context: .
        dockerfile: Dockerfile_php
      environment:
          PHP_IDE_CONFIG: "serverName=jeophpardy.local"
      volumes:
          - ../Code/:/var/www/jeophpardy

  jeophpardy_db:
      container_name: jeophpardy_db
      image: mysql:latest
      environment:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
          MYSQL_DATABASE: jeophpardy
      ports:
          - "3308:3306"
      restart: always
      volumes:
          - ../mysql-data:/var/lib/mysql