FROM php:7-fpm

RUN apt-get update && apt-get install -y \
  autoconf \
  automake \
  gcc \
  git \
  openssh-client \
  valgrind \
  vim

RUN apt-get install -y git unzip libpng-dev wget default-jre mysql-client libmysql-java libjpeg62-turbo-dev libfreetype6-dev; \
    pecl install xdebug ; \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer ; \
    composer --version ; \
    echo "Europe/Berlin" > /etc/timezone ; \
    dpkg-reconfigure -f noninteractive tzdata ; \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/; \
    docker-php-ext-install pdo pdo_mysql mysqli calendar pcntl opcache gd   ; \
    docker-php-ext-enable xdebug; \
    apt-get clean ; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ; \
    usermod -u 1000 www-data ; \
    groupmod -g 1000 www-data

WORKDIR /var/www/jeopardy