version: "2.0"
services:
  jeophardy_nginx:
    image: nginx:latest
    volumes:
      - ../Code/:/var/www/jeophpardy
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "8080:80"
    links:
      - jeophpardy_php
      - jeophpardy_db

  jeophpardy_php:
      build:
        context: .
        dockerfile: Dockerfile_php
      environment:
          PHP_IDE_CONFIG: "serverName=jeophpardy.local"
      volumes:
          - ../Code/:/var/www/jeophpardy

  jeophpardy_db:
      container_name: jeophpardy_db
      image: postgres:latest
      ports:
          - "3308:3306"
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
