FROM php:7-fpm-alpine

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN apk update 
RUN apk add \
  git \
  openssh-client \
  vim \
  libzip-dev \
  zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer ; \
    composer --version ; \
    echo "Europe/Berlin" > /etc/timezone

RUN docker-php-ext-install pdo calendar pcntl opcache zip

RUN composer global require hirak/prestissimo

# exec into docker with "sh -l" to load profile aliases
RUN echo "alias checkCode='/var/www/jeophpardy/vendor/bin/phpunit && /var/www/jeophpardy/vendor/bin/phpcs --standard=PSR2 Controller/ '" >> /root/.profile

WORKDIR /var/www/jeophpardy
