FROM node:10-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./Code/NodeJS/package*.json ./Code/NodeJS/yarn.lock ./

RUN yarn install

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./Code/NodeJS/ .

CMD [ "node", "server.js" ]
