version: "2.0"
services:
  jeophardy_nginx:
    image: nginx:latest
    volumes:
      - ../Code/PHP:/var/www/jeophpardy
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - jeophpardy_php

  jeophpardy_php:
      build:
        context: .
        dockerfile: Dockerfile_php
      environment:
          PHP_IDE_CONFIG: "serverName=jeophpardy.local"
      volumes:
          - ../Code/PHP:/var/www/jeophpardy