version: "2.0"
services:
  jeophardy_nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ../Code/Elm/assets/css
        target: /var/www/jeophpardy/web/css/elm
      - type: bind
        source: ../Code/Elm/assets/mp3
        target: /var/www/jeophpardy/web/mp3
      - type: bind
        source: ./gameFiles/
        target: /var/www/jeophpardy/web/gameFiles
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  jeopardy_node:
    build:
      context: ..
      dockerfile: Docker/Dockerfile_node
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
