services:
  database:
    class: mgbs\Library\Database
    arguments: [ "%db_type%", "%db_path%" ]

  questionmodel:
    class: mgbs\Model\Questions
    arguments: ['@database']

  indexcontroller:
    class: mgbs\Library\IndexController
    arguments: ['@questionmodel']