services:
  database:
    class: mgbs\Library\Database
    arguments: [ "%db_type%", "%db_path%" ]

  questionmodel:
    class: mgbs\Model\QuestionsModel
    arguments: ['@database']
    calls:
        - [setTableName, ['questions']]
