name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0

    - name: yarn install and test
      working-directory: ./Code/NodeJS
      run: |
        yarn install
        yarn test --coverage
      env:
        CI: true
    - name: Upload coverage reports to Codecov
      run: |
          bash <(curl -s https://codecov.internal.dev.ampeers.cloud/bash) \
          -t ${{ secrets.CODECOV_TOKEN }} \
          -f ./Code/NodeJS/coverage/lcov.info \
          -u https://codecov.internal.dev.ampeers.cloud
