name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: yarn install and test
      working-directory: ./Code/NodeJS
      run: |
        yarn install
        yarn test
      env:
        CI: true
